pipeline:
  name: pipeline-secrets
  identifier: pipelinesecrets
  projectIdentifier: lab
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: GET_SECRET_TO_DEPLOY
                  identifier: GET_SECRET_TO_DEPLOY
                  spec:
                    shell: Sh
                    command: |-
                      echo 'text secret is: <+secrets.getValue("MY_FIRST_SECRET")>'
                      export my_first_secret='<+secrets.getValue("MY_FIRST_SECRET")>'
                      echo '<+stage.variables.VARIABLE_ONE>'
                      echo '<+stage.variables.VARIABLE_TWO>'
                      echo '<+pipeline.variables.get("VARIAVEL_GLOBAL_DA_PIPELINE")>'
                    outputVariables:
                      - name: my_first_secret
                        type: String
                        value: my_first_secret
              - step:
                  type: Run
                  name: SHOW_SECRET_FOR_DEBUG
                  identifier: SHOW_SECRET_FOR_DEBUG
                  spec:
                    shell: Sh
                    command: |-
                      echo <+steps.GET_SECRET_TO_DEPLOY.output.outputVariables.my_first_secret>
                      echo <+execution.steps.GET_SECRET_TO_DEPLOY.output.outputVariables.my_first_secret>
                  when:
                    stageStatus: Success
                    condition: <+stage.variables.FEATURE_FLAG_EXECUTION> != "0"
        variables:
          - name: VARIABLE_ONE
            type: String
            description: ""
            required: false
            value: <+input>
          - name: VARIABLE_TWO
            type: String
            description: ""
            required: true
            value: <+input>
          - name: FEATURE_FLAG_EXECUTION
            type: String
            description: ""
            required: true
            value: <+input>
  variables:
    - name: VARIAVEL_GLOBAL_DA_PIPELINE
      type: String
      description: ""
      required: true
      value: <+input>
