pipeline:
  identifier: default
  name: default
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
  stages:
  - stage:
      identifier: test
      name: test
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: setupgo
              name: Set up Go
              spec:
                uses: actions/setup-go@v5
                with:
                  go-version: "1.21"
              timeout: ""
              type: Action
          - step:
              identifier: cachegomodules
              name: Cache Go modules
              spec:
                uses: actions/cache@v3
                with:
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  path: ~/go/pkg/mod
                  restore-keys: |
                    ${{ runner.os }}-go-
              timeout: ""
              type: Action
          - step:
              identifier: downloaddependencies
              name: Download dependencies
              spec:
                command: go mod download
              timeout: ""
              type: Run
          - step:
              identifier: runtests
              name: Run tests
              spec:
                command: go test -v -race -coverprofile=coverage.out ./...
              timeout: ""
              type: Run
          - step:
              identifier: uploadcoverage
              name: Upload coverage
              spec:
                uses: codecov/codecov-action@v3
                with:
                  files: ./coverage.out
              timeout: ""
              type: Action
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
  - stage:
      identifier: lint
      name: lint
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: setupgo1
              name: Set up Go
              spec:
                uses: actions/setup-go@v5
                with:
                  go-version: "1.21"
              timeout: ""
              type: Action
          - step:
              identifier: rungolangcilint
              name: Run golangci-lint
              spec:
                uses: golangci/golangci-lint-action@v3
                with:
                  version: latest
              timeout: ""
              type: Action
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
  - stage:
      identifier: build1
      name: build
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: setupgo2
              name: Set up Go
              spec:
                uses: actions/setup-go@v5
                with:
                  go-version: "1.21"
              timeout: ""
              type: Action
          - step:
              identifier: build
              name: Build
              spec:
                command: go build -v -o app ./cmd/main.go
              timeout: ""
              type: Run
          - step:
              identifier: uploadartifact
              name: Upload artifact
              spec:
                uses: actions/upload-artifact@v3
                with:
                  name: go-app
                  path: app
              timeout: ""
              type: Action
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
  - stage:
      identifier: docker
      name: docker
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              identifier: setupdockerbuildx
              name: Set up Docker Buildx
              spec:
                uses: docker/setup-buildx-action@v3
              timeout: ""
              type: Action
          - step:
              identifier: logintodockerhub
              name: Login to Docker Hub
              spec:
                uses: docker/login-action@v3
                with:
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  username: ${{ secrets.DOCKER_USERNAME }}
              timeout: ""
              type: Action
          - step:
              identifier: buildandpush
              name: Build and push
              spec:
                uses: docker/build-push-action@v5
                with:
                  context: .
                  push: "true"
                  tags: yourusername/your-app:latest,yourusername/your-app:${{ github.sha
                    }}
              timeout: ""
              type: Action
        platform:
          arch: Amd64
          os: Linux
        runtime:
          spec: {}
          type: Cloud
      type: CI
      when:
        pipelineStatus: Success
