
---
# Source: luffy-apps/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: luffy-services
  labels:
    helm.sh/chart: luffy-apps-0.1.0
    app.kubernetes.io/name: luffy-apps
    app.kubernetes.io/instance: luffy-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: luffy-apps/templates/service.yaml
# Regular Service (when not using blue-green)
apiVersion: v1
kind: Service
metadata:
  name: luffy-services
  labels:
    helm.sh/chart: luffy-apps-0.1.0
    app.kubernetes.io/name: luffy-apps
    app.kubernetes.io/instance: luffy-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: luffy-apps
    app.kubernetes.io/instance: luffy-app
---
# Source: luffy-apps/templates/rollouts.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: luffy-services
  labels:
    helm.sh/chart: luffy-apps-0.1.0
    app.kubernetes.io/name: luffy-apps
    app.kubernetes.io/instance: luffy-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: luffy-apps
      app.kubernetes.io/instance: luffy-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: luffy-apps
        app.kubernetes.io/instance: luffy-app
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: luffy-services
      securityContext:
        {}
      containers:
        - name: luffy-apps
          securityContext:
            {}
          image: "560978416398.dkr.ecr.us-east-1.amazonaws.com/luffy-services:v5.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {}
        - setWeight: 100
---
# Source: luffy-apps/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "luffy-services-test-connection"
  labels:
    helm.sh/chart: luffy-apps-0.1.0
    app.kubernetes.io/name: luffy-apps
    app.kubernetes.io/instance: luffy-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['luffy-services:80']
  restartPolicy: Never