pipeline:
  name: aws_hosted
  identifier: aws_hosted
  projectIdentifier: grand_line
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        repoName: goHelloWorldServer
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-ci-pool
                os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub_main
                    repo: idasilva6/hello
                    tags:
                      - "<+pipeline.sequenceId> "
