pipeline:
  name: azure_hosted
  identifier: azure_hosted
  projectIdentifier: grand_line
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        repoName: goHelloWorldServer
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-azure-pool
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: echo "building"
