trigger:
  name: ${TRIGGER_NAME}
  identifier: ${TRIGGER_IDENTIFIER}
  enabled: true
  description: "Automatically triggers CD pipeline on Pull Request Merge events"
  tags: {}
  projectIdentifier: ${PROJECT_ID}
  orgIdentifier: ${ORG_ID}
  pipelineIdentifier: ${PIPELINE_ID}
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: ${GITHUB_CONNECTOR}
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: ${TARGET_BRANCH}
          headerConditions: []
          repoName: harness
          actions:
            - Close
  inputYaml: |
    pipeline:
      identifier: cd_deploy
      properties:
        ci:
          codebase:
            build:
              type: PR
              spec:
                number: <+trigger.prNumber>
            repoName: harness