pipeline:
  name: ${PIPELINE_NAME}
  identifier: ${PIPELINE_IDENTIFIER}
  projectIdentifier: ${PROJECT_ID_PLACEHOLDER}
  orgIdentifier: ${ORG_ID_PLACEHOLDER}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        build: <+input>
        repoName: <+input>  
        branch: main
        path: services/luffy
  stages:
    - stage:
        name: Deploy To Development
        identifier: Deploy_To_Development
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: luffy_development
          environment:
            environmentRef: development
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s_development
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Verify Signature - Cosign DEV
                  identifier: Verify_Signature_Cosign
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: set -e
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                contextType: Pipeline
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: OWASP ZAP
        identifier: OWASP_ZAP
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Zap
                  name: OWASP ZAP
                  identifier: OWASP_ZAP
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: instance
                      detection: auto
                    advanced:
                      log:
                        level: info
                    instance:
                      domain: https://tamekia-uneternized-alease.ngrok-free.dev
                      protocol: https
                      path: v1/version
    - stage:
        name: Approval Gate - Staging
        identifier: Approval_Gate_Staging
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval - QA
                  identifier: Approval_QA
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy To Staging
        identifier: Deploy_To_Staging
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: luffy_staging
          environment:
            environmentRef: staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s_staging
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Verify Signature - Cosign STG
                  identifier: Verify_Signature_Cosign_STG
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: set -e
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Approval Gate - Production
        identifier: Approval_Gate_Production
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval - Stackholders
                  identifier: Approval_Stackholders
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: Deploy to Production
        identifier: Deploy_to_Production
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: luffy_production
          environment:
            environmentRef: production
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s_production
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Verify Signature - Cosign PROD
                  identifier: Verify_Signature_Cosign_PROD
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: set -e
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback