apiVersion: gitops.harness.io/v1alpha1
kind: GitopsAgent
metadata:
  labels:
    app.kubernetes.io/name: gitops-agent-project1_gitops_agent
    app.kubernetes.io/managed-by: Harness
    app.kubernetes.io/version: v0.104.0
    app.kubernetes.io/component: gitops-agent
  name: gitops-agent-project1_gitops_agent
spec:
  identity:
    accountIdentifier: 9leDao-yRqu7DN66CVDAeg
    orgIdentifier:  default
    projectIdentifier: project1
    agentIdentifier: project1_gitops_agent
    agentName: project1-gitops-agent
  secrets:
    agentSecret: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUREK0NhZzVSZEVaeWRJCjNoa0gvNTRURlV5T01Ld0plWjROcE4zQjBlRmxMWVh2RUMrVEg0bG1TY3VrU2N5SnNPaTlDOUJ4bGN1M1hOME4KalZGRys4aEsxbUtBdVQ2L1JhbWE3VlpzczhuMWt4NlUyNWxJdk4rWlJQNG9vWlp3ZWhpdHFOUkg1bnpDTWwwegovaXpBdGxlOTM3M1ZDVUdqL2huUEhwdGdLbTNXTVVPUkhUL2tWV2hKSlpKZkNZbEtpN2xkT3UrejZUdHhOMWJUCnZLdGNDbnFvbzEwSVlQMGZQY1FJUjE4OWtZbjV5RFlKdm1zUWwxamx0ZHFqUFpWS0lORlFRZXZQaE1uQ0N1dEQKYlBWRUkvalovbUlmelFuVWlrT3JlOHJUK2JzNjNlNmpvZS9PL3ZxWFJpdFNSTEFlMnFFNmIzRURDNCtpKythWQpydzc1dXlDVkFnTUJBQUVDZ2dFQUVTTUxKYmpDM3gxeUp3SWRDRUVITHI0SEVzd1l6ejlPWGYwVDAxWXFNckhYCmEzOXIyWjdCWWl1RDNsc0J3dXl3ZlkraDY3emdzcWt4UDNVakxXVHBML290WlBwT0RXWG5IZ0F4TlpKSFQrMU0KbUZIWHhxK1ZrZzZoZHlZaVJMVzRvTDhKeVR2VG54dk9ZTFNTYjB2Q3duemxXZExVWmFYYjFldmtSSFdSWTFDRwpUQUoydGVibDN6NVRmeWlWblJvdXVUTUdrQ21iQ2xmcmdYeFhIc3Z5Z2ZEL09wLy9XdGNoeVZyNy9pNmFKS1NBCnFuZjhPTTVQWWY1clFLZ1FGd0V0cWpWNXF4c1VqS00yMnVHNjZEb01lQzdpRHdYSFFlU0h3SHNJMXpFSFpGbnUKQjVucjVxMXBmaGMzNGJaL1dhWlR3MXdTV0tqYWtBNUQrRjhFKzB1emdRS0JnUUR1QzhzcnJ4UVZReWdENm5TcgpBRHZ5M0JQOVhsc0hlQkFWUHlGS2NTRXpjcWVBUk1HRGtnTERQSXBnbFdEOUV4aWlTQVk1SmMvSUxvYW5qK0syCjJyQzQwdWJvTVV0dCtUbzBRT3FQT0NrQ0I1YnhCM3pMOFk2di85TXl4eXRlL3RUVEQrclNXOUlkV1huRzlaMUYKcG9sZTNvR2d5aXJWaWpZN25PUXgwclhlSVFLQmdRRFN2Ky8vWURNc21maWNHa0dvMWNkR0VDWmdaQnd5b3F6ZQpjT3hLMkVmMnJWRmFGQnRqY3BYM2NDMGsxNE00QkxndlFJRzJVNHpSRWd6NHgxdTZtNE80WTN4WHl6ZWh2ODE2CkNDZi9UeW84NWRISjV0OHJ6MjFTSTkrUlMzdW11ZHJRTWpSTS92bnUvMUdrVk4xVU45Uk05YkF1ekpjbGg5UHEKa0hQVkRaNHI5UUtCZ0hHbkc5ZTlmWDh4VXhlYmh4eGx2am1UcmMrWWp5bWZ2ejRGcUNWY29oZG9OR1RmYnUwYwpkMGt6ekhXVW5IdjM5QmoyL2xHbXBlL1RsdUxGcGQ3Ynh1aFhlWHQrblo3aUVWSUZkSGZ3dmxPRHdDTlFDZHR0CmQweThmZCtPakR5TXVwd1N5M0NuK2tlZEFyRmxiek5qOGM1anVjeEUrZkorVEtwbG0rWFZ6cE5CQW9HQkFKcUgKYmp5OGx3bGZKTEdoZHYrTE1RQ29tdHNXeks0OEpiRTg3Nlc1akpyTlh0ZEQ0d2s2WGNmL0VycnU0eUpTSTVOUwpJMHBEWFA5MzB0Y2ZwcHpmcHVldTJ0K3MvRyszcWJ5TytuVHo0UzZoL1Ara0w0TjZKdGlSd1Q1U01LcUJvSFlFCk9lRXpIS1FueGY5TzByTUw5TGt4ZFN2N2krQlRCZ242UFZTOUZYdDVBb0dCQU8wU3NKM0FEZ1hXTHpxSXM1TjUKcEZoTVF5cStEUmdnYUJzVDRpQ0EyL0RTTFcxYUkranpXTitCd3VxREl0SjNvUG0yTGNKV3FGRWR6ejNlWGRHagpYNWQ3TzNDRVRlMnFvMlBrS0hmK1FRNDQvV2h4aGUva1FaRFlONi93YmlRbXhTMWd5d3Jjd1ArVlkzNWNYN3I2Cm9tRytMdW1iNENjOHRsVGxaUTZ1cERERwotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  target:
    http: https://app.harness.io/gitops
    protocol: HTTP1
  logLevel:  debug
  image: docker.io/harness/gitops-agent:v0.104.0
  replicas: 1
  fipsEnabled: false
  upgrade:
    enabled: true
    image: docker.io/harness/upgrader:latest