trigger:
  name: ${TRIGGER_NAME}
  identifier: ${TRIGGER_IDENTIFIER}
  enabled: true
  description: "Automatically triggers CI pipeline on Pull Request events"
  tags: {}
  projectIdentifier: ${PROJECT_ID}
  orgIdentifier: ${ORG_ID}
  pipelineIdentifier: ${PIPELINE_ID}
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: ${GITHUB_CONNECTOR}
          autoAbortPreviousExecutions: true
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: ${TARGET_BRANCH}
            - key: changedFiles
              operator: Contains
              value: /services/usopp
          headerConditions: []
          repoName: harness
          actions:
            - Open
            - Reopen
            - Synchronize
  inputYaml: |
    pipeline:
      identifier: ci_build_push_java
      properties:
        ci:
          codebase:
            build:
              type: PR
              spec:
                number: <+trigger.prNumber>
            repoName: harness