fullnameOverride: luffy-services
replicaCount: 4
image:
  repository: 560978416398.dkr.ecr.us-east-1.amazonaws.com/luffy-services
  tag: v9.0.0
imagePullSecrets:
  - name: regcred
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
