pipeline:
  name: ${PIPELINE_NAME}
  identifier: ${PIPELINE_IDENTIFIER}
  projectIdentifier: ${PROJECT_ID_PLACEHOLDER}
  orgIdentifier: ${ORG_ID_PLACEHOLDER}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        build: <+input>
  stages:
    - stage:
        name: Build and Push
        identifier: build_push
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                    type: BuildAndPushDockerRegistry
                    name: BuildAndPushDockerRegistry_1
                    identifier: BuildAndPushDockerRegistry_1
                    spec:
                      connectorRef: dockerhub_main
                      repo: idasilva6/luffy
                      tags:
                        - v1.0.3