pipeline:
  name: ${PIPELINE_NAME}
  identifier: ${PIPELINE_IDENTIFIER}
  projectIdentifier: ${PROJECT_ID_PLACEHOLDER}
  orgIdentifier: ${ORG_ID_PLACEHOLDER}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        build: <+input>
        repoName: <+input>  
        branch: main
        path: services/luffy
  stages:
    - stage:
        name: Continuous Integration
        identifier: build_push
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Gitleaks
                  name: Gitleaks
                  identifier: Gitleaks
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
              - step:
                  type: Run
                  name: Golang Lint
                  identifier: Golang_Lint
                  spec:
                    connectorRef: dockerhub_main
                    image: golangci/golangci-lint:v1.61-alpine
                    shell: Sh
                    command: |-
                      set -e
                      cd  /harness/services/luffy

                      golangci-lint run \
                          --timeout=5m \
                          --out-format=checkstyle \
                          --issues-exit-code=0 \
                          ./... > lint-report.xml || true

                      golangci-lint run \
                          --timeout=5m \
                          --out-format=colored-line-number \
                          ./...
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/services/luffy/lint-report.xml
              - step:
                  type: Owasp
                  name: OWASP Dependency-Check
                  identifier: Owasp
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
                      args:
                        cli: "--disableOssIndex"
              - step:
                  type: Run
                  identifier: installgo
                  name: Install Go
                  spec:
                    connectorRef: dockerhub_main
                    image: golang:1.23-alpine
                    shell: Sh
                    workingDirectory: /harness/services/luffy
                    command: |-
                      set -e
                      go version
                      export GOPATH=/root/go
                      export PATH=$GOPATH/bin:$PATH
                      go install github.com/jstemmer/go-junit-report/v2@latest
              - step:
                  type: Run
                  identifier: test
                  name: Test
                  spec:
                    connectorRef: dockerhub_main
                    image: golang:1.23-alpine
                    shell: Sh
                    workingDirectory: /harness/services/luffy
                    command: |-
                      set -e
                      cd  /harness/services/luffy
                      export GOPATH=/root/go
                      export PATH=$GOPATH/bin:$PATH
                      go version
                      go mod download
                      go install github.com/jstemmer/go-junit-report/v2@latest
                      go test -v ./... 2>&1 | tee report.out
                      cat report.out | go-junit-report -set-exit-code > report.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/services/luffy/report.xml
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub_main
                    repo: idasilva6/luffy
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: services/luffy/Dockerfile
                    context: services/luffy
              - step:
                  type: AquaTrivy
                  name: AquaTrivy_1
                  identifier: AquaTrivy_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    image:
                      type: docker_v2
                      tag: <+pipeline.sequenceId>
                      name: idasilva6/luffy
